// AUTO-GENERATED by scripts/generate-hero-assets.mjs — do not edit by hand.
// Explicit imports so Vite emits + fingerprints every variant.

import bg_640_webp from "./bg-640.webp";
import bg_640_avif from "./bg-640.avif";
import bg_1280_webp from "./bg-1280.webp";
import bg_1280_avif from "./bg-1280.avif";
import bg_1920_webp from "./bg-1920.webp";
import bg_1920_avif from "./bg-1920.avif";
import fog_7_640_webp from "./fog-7-640.webp";
import fog_7_640_avif from "./fog-7-640.avif";
import fog_7_1280_webp from "./fog-7-1280.webp";
import fog_7_1280_avif from "./fog-7-1280.avif";
import fog_7_1900_webp from "./fog-7-1900.webp";
import fog_7_1900_avif from "./fog-7-1900.avif";
import fog_7_1920_webp from "./fog-7-1920.webp";
import fog_7_1920_avif from "./fog-7-1920.avif";
import mountain_10_640_webp from "./mountain-10-640.webp";
import mountain_10_640_avif from "./mountain-10-640.avif";
import mountain_10_1200_webp from "./mountain-10-1200.webp";
import mountain_10_1200_avif from "./mountain-10-1200.avif";
import mountain_10_1280_webp from "./mountain-10-1280.webp";
import mountain_10_1280_avif from "./mountain-10-1280.avif";
import mountain_10_1837_webp from "./mountain-10-1837.webp";
import mountain_10_1837_avif from "./mountain-10-1837.avif";
import fog_6_640_webp from "./fog-6-640.webp";
import fog_6_640_avif from "./fog-6-640.avif";
import fog_6_1280_webp from "./fog-6-1280.webp";
import fog_6_1280_avif from "./fog-6-1280.avif";
import fog_6_1920_webp from "./fog-6-1920.webp";
import fog_6_1920_avif from "./fog-6-1920.avif";
import mountain_9_640_webp from "./mountain-9-640.webp";
import mountain_9_640_avif from "./mountain-9-640.avif";
import mountain_9_670_webp from "./mountain-9-670.webp";
import mountain_9_670_avif from "./mountain-9-670.avif";
import mountain_9_1280_webp from "./mountain-9-1280.webp";
import mountain_9_1280_avif from "./mountain-9-1280.avif";
import mountain_9_1340_webp from "./mountain-9-1340.webp";
import mountain_9_1340_avif from "./mountain-9-1340.avif";
import fog_5_640_webp from "./fog-5-640.webp";
import fog_5_640_avif from "./fog-5-640.avif";
import fog_5_650_webp from "./fog-5-650.webp";
import fog_5_650_avif from "./fog-5-650.avif";
import fog_5_819_webp from "./fog-5-819.webp";
import fog_5_819_avif from "./fog-5-819.avif";
import mountain_7_640_webp from "./mountain-7-640.webp";
import mountain_7_640_avif from "./mountain-7-640.avif";
import mountain_7_738_webp from "./mountain-7-738.webp";
import mountain_7_738_avif from "./mountain-7-738.avif";
import mountain_7_951_webp from "./mountain-7-951.webp";
import mountain_7_951_avif from "./mountain-7-951.avif";
import mountain_6_408_webp from "./mountain-6-408.webp";
import mountain_6_408_avif from "./mountain-6-408.avif";
import mountain_6_640_webp from "./mountain-6-640.webp";
import mountain_6_640_avif from "./mountain-6-640.avif";
import mountain_6_719_webp from "./mountain-6-719.webp";
import mountain_6_719_avif from "./mountain-6-719.avif";
import fog_4_590_webp from "./fog-4-590.webp";
import fog_4_590_avif from "./fog-4-590.avif";
import fog_4_640_webp from "./fog-4-640.webp";
import fog_4_640_avif from "./fog-4-640.avif";
import fog_4_1030_webp from "./fog-4-1030.webp";
import fog_4_1030_avif from "./fog-4-1030.avif";
import mountain_5_640_webp from "./mountain-5-640.webp";
import mountain_5_640_avif from "./mountain-5-640.avif";
import mountain_5_725_webp from "./mountain-5-725.webp";
import mountain_5_725_avif from "./mountain-5-725.avif";
import mountain_5_1100_webp from "./mountain-5-1100.webp";
import mountain_5_1100_avif from "./mountain-5-1100.avif";
import fog_3_640_webp from "./fog-3-640.webp";
import fog_3_640_avif from "./fog-3-640.avif";
import fog_3_1280_webp from "./fog-3-1280.webp";
import fog_3_1280_avif from "./fog-3-1280.avif";
import fog_3_1600_webp from "./fog-3-1600.webp";
import fog_3_1600_avif from "./fog-3-1600.avif";
import fog_3_1920_webp from "./fog-3-1920.webp";
import fog_3_1920_avif from "./fog-3-1920.avif";
import mountain_4_640_webp from "./mountain-4-640.webp";
import mountain_4_640_avif from "./mountain-4-640.avif";
import mountain_4_1100_webp from "./mountain-4-1100.webp";
import mountain_4_1100_avif from "./mountain-4-1100.avif";
import mountain_4_1280_webp from "./mountain-4-1280.webp";
import mountain_4_1280_avif from "./mountain-4-1280.avif";
import mountain_4_1393_webp from "./mountain-4-1393.webp";
import mountain_4_1393_avif from "./mountain-4-1393.avif";
import mountain_3_630_webp from "./mountain-3-630.webp";
import mountain_3_630_avif from "./mountain-3-630.avif";
import mountain_3_640_webp from "./mountain-3-640.webp";
import mountain_3_640_avif from "./mountain-3-640.avif";
import mountain_3_819_webp from "./mountain-3-819.webp";
import mountain_3_819_avif from "./mountain-3-819.avif";
import fog_2_640_webp from "./fog-2-640.webp";
import fog_2_640_avif from "./fog-2-640.avif";
import fog_2_1100_webp from "./fog-2-1100.webp";
import fog_2_1100_avif from "./fog-2-1100.avif";
import fog_2_1280_webp from "./fog-2-1280.webp";
import fog_2_1280_avif from "./fog-2-1280.avif";
import fog_2_1920_webp from "./fog-2-1920.webp";
import fog_2_1920_avif from "./fog-2-1920.avif";
import mountain_2_640_webp from "./mountain-2-640.webp";
import mountain_2_640_avif from "./mountain-2-640.avif";
import mountain_2_800_webp from "./mountain-2-800.webp";
import mountain_2_800_avif from "./mountain-2-800.avif";
import mountain_2_1209_webp from "./mountain-2-1209.webp";
import mountain_2_1209_avif from "./mountain-2-1209.avif";
import mountain_1_640_webp from "./mountain-1-640.webp";
import mountain_1_640_avif from "./mountain-1-640.avif";
import mountain_1_954_webp from "./mountain-1-954.webp";
import mountain_1_954_avif from "./mountain-1-954.avif";
import fog_1_640_webp from "./fog-1-640.webp";
import fog_1_640_avif from "./fog-1-640.avif";
import fog_1_1280_webp from "./fog-1-1280.webp";
import fog_1_1280_avif from "./fog-1-1280.avif";
import fog_1_1900_webp from "./fog-1-1900.webp";
import fog_1_1900_avif from "./fog-1-1900.avif";
import fog_1_1920_webp from "./fog-1-1920.webp";
import fog_1_1920_avif from "./fog-1-1920.avif";

/** stem -> fingerprinted URLs, e.g. "bg-1920" -> { webp, avif } */
export const HERO_ASSET_URLS: Record<string, { webp: string; avif: string }> = {
  "bg-640": { webp: bg_640_webp, avif: bg_640_avif },
  "bg-1280": { webp: bg_1280_webp, avif: bg_1280_avif },
  "bg-1920": { webp: bg_1920_webp, avif: bg_1920_avif },
  "fog-7-640": { webp: fog_7_640_webp, avif: fog_7_640_avif },
  "fog-7-1280": { webp: fog_7_1280_webp, avif: fog_7_1280_avif },
  "fog-7-1900": { webp: fog_7_1900_webp, avif: fog_7_1900_avif },
  "fog-7-1920": { webp: fog_7_1920_webp, avif: fog_7_1920_avif },
  "mountain-10-640": { webp: mountain_10_640_webp, avif: mountain_10_640_avif },
  "mountain-10-1200": { webp: mountain_10_1200_webp, avif: mountain_10_1200_avif },
  "mountain-10-1280": { webp: mountain_10_1280_webp, avif: mountain_10_1280_avif },
  "mountain-10-1837": { webp: mountain_10_1837_webp, avif: mountain_10_1837_avif },
  "fog-6-640": { webp: fog_6_640_webp, avif: fog_6_640_avif },
  "fog-6-1280": { webp: fog_6_1280_webp, avif: fog_6_1280_avif },
  "fog-6-1920": { webp: fog_6_1920_webp, avif: fog_6_1920_avif },
  "mountain-9-640": { webp: mountain_9_640_webp, avif: mountain_9_640_avif },
  "mountain-9-670": { webp: mountain_9_670_webp, avif: mountain_9_670_avif },
  "mountain-9-1280": { webp: mountain_9_1280_webp, avif: mountain_9_1280_avif },
  "mountain-9-1340": { webp: mountain_9_1340_webp, avif: mountain_9_1340_avif },
  "fog-5-640": { webp: fog_5_640_webp, avif: fog_5_640_avif },
  "fog-5-650": { webp: fog_5_650_webp, avif: fog_5_650_avif },
  "fog-5-819": { webp: fog_5_819_webp, avif: fog_5_819_avif },
  "mountain-7-640": { webp: mountain_7_640_webp, avif: mountain_7_640_avif },
  "mountain-7-738": { webp: mountain_7_738_webp, avif: mountain_7_738_avif },
  "mountain-7-951": { webp: mountain_7_951_webp, avif: mountain_7_951_avif },
  "mountain-6-408": { webp: mountain_6_408_webp, avif: mountain_6_408_avif },
  "mountain-6-640": { webp: mountain_6_640_webp, avif: mountain_6_640_avif },
  "mountain-6-719": { webp: mountain_6_719_webp, avif: mountain_6_719_avif },
  "fog-4-590": { webp: fog_4_590_webp, avif: fog_4_590_avif },
  "fog-4-640": { webp: fog_4_640_webp, avif: fog_4_640_avif },
  "fog-4-1030": { webp: fog_4_1030_webp, avif: fog_4_1030_avif },
  "mountain-5-640": { webp: mountain_5_640_webp, avif: mountain_5_640_avif },
  "mountain-5-725": { webp: mountain_5_725_webp, avif: mountain_5_725_avif },
  "mountain-5-1100": { webp: mountain_5_1100_webp, avif: mountain_5_1100_avif },
  "fog-3-640": { webp: fog_3_640_webp, avif: fog_3_640_avif },
  "fog-3-1280": { webp: fog_3_1280_webp, avif: fog_3_1280_avif },
  "fog-3-1600": { webp: fog_3_1600_webp, avif: fog_3_1600_avif },
  "fog-3-1920": { webp: fog_3_1920_webp, avif: fog_3_1920_avif },
  "mountain-4-640": { webp: mountain_4_640_webp, avif: mountain_4_640_avif },
  "mountain-4-1100": { webp: mountain_4_1100_webp, avif: mountain_4_1100_avif },
  "mountain-4-1280": { webp: mountain_4_1280_webp, avif: mountain_4_1280_avif },
  "mountain-4-1393": { webp: mountain_4_1393_webp, avif: mountain_4_1393_avif },
  "mountain-3-630": { webp: mountain_3_630_webp, avif: mountain_3_630_avif },
  "mountain-3-640": { webp: mountain_3_640_webp, avif: mountain_3_640_avif },
  "mountain-3-819": { webp: mountain_3_819_webp, avif: mountain_3_819_avif },
  "fog-2-640": { webp: fog_2_640_webp, avif: fog_2_640_avif },
  "fog-2-1100": { webp: fog_2_1100_webp, avif: fog_2_1100_avif },
  "fog-2-1280": { webp: fog_2_1280_webp, avif: fog_2_1280_avif },
  "fog-2-1920": { webp: fog_2_1920_webp, avif: fog_2_1920_avif },
  "mountain-2-640": { webp: mountain_2_640_webp, avif: mountain_2_640_avif },
  "mountain-2-800": { webp: mountain_2_800_webp, avif: mountain_2_800_avif },
  "mountain-2-1209": { webp: mountain_2_1209_webp, avif: mountain_2_1209_avif },
  "mountain-1-640": { webp: mountain_1_640_webp, avif: mountain_1_640_avif },
  "mountain-1-954": { webp: mountain_1_954_webp, avif: mountain_1_954_avif },
  "fog-1-640": { webp: fog_1_640_webp, avif: fog_1_640_avif },
  "fog-1-1280": { webp: fog_1_1280_webp, avif: fog_1_1280_avif },
  "fog-1-1900": { webp: fog_1_1900_webp, avif: fog_1_1900_avif },
  "fog-1-1920": { webp: fog_1_1920_webp, avif: fog_1_1920_avif },
};
